import Test from 'node:test';
import Assert from 'node:assert/strict';
import { CreateAccountChangeHandler } from '../api/AccountChange.js';
import { AccountEnglish, AccountMalay } from '../Src/Locales/Account.js';
function Fixture(Overrides = {}) {
    const Calls=[];const Env={AccountChangesEnabled:'true',PINChangesEnabled:'true',SUPABASE_URL:'https://example.invalid',SUPABASE_ANON_KEY:'public',SUPABASE_SERVICE_ROLE_KEY:'private',...Overrides.Env};
    const Auth={auth:{getUser:async()=>({data:{user:{id:'user-a',email:'old@example.invalid'}}}),signInWithPassword:async Input=>{Calls.push(['Verify',Input]);return Overrides.Wrong?{error:{}}:{data:{user:{id:Overrides.Other?'user-b':'user-a'},session:{}}}},updateUser:async Input=>{Calls.push(['Update',Input]);return {data:{}}},signOut:async Input=>{Calls.push(['SignOut',Input]);return {error:Overrides.SignOutError?{}:null}}}};
    const Database={rpc:async(Name,Input)=>{Calls.push([Name,Input]);return Name==='ConsumeLoginAttempt'?{data:{Allowed:!Overrides.Limited},error:Overrides.LimitError?{}:null}:{data:true}},from:()=>({select:()=>({eq:()=>({single:async()=>({data:{IsActive:true,Role:'Manager'}})})})})};
    const Handler=CreateAccountChangeHandler({Env,Client:(_URL,Key)=>Key==='public'?Auth:Database});
    const Req={method:'POST',headers:{origin:'https://www.hghsejahtera.my','content-type':'application/json',authorization:'Bearer token'},socket:{remoteAddress:'127.0.0.1'},body:{Action:'Username',Value:'new-name',CurrentPassword:'old-password'}};
    const Res={Status:0,Body:null,setHeader(){},status(Value){this.Status=Value;return this},json(Value){this.Body=Value;return this}};
    return {Calls,Req,Res,Run:()=>Handler(Req,Res)};
}
Test('disabled rollout performs no authentication or writes',async()=>{const F=Fixture({Env:{AccountChangesEnabled:'false'}});await F.Run();Assert.equal(F.Res.Status,503);Assert.equal(F.Calls.length,0)});
Test('missing password and invalid values fail before verification',async()=>{for(const Body of [{Action:'Username',Value:'ok-name'}, {Action:'Password',Value:'short',CurrentPassword:'old'},{Action:'SetPIN',Value:'abcd',CurrentPassword:'old'}]){const F=Fixture();F.Req.body=Body;await F.Run();Assert.equal(F.Res.Status,400);Assert.equal(F.Calls.length,0)}});
Test('untrusted origin and missing session cannot change account',async()=>{for(const Field of ['origin','authorization']){const F=Fixture();delete F.Req.headers[Field];await F.Run();Assert.ok([401,403].includes(F.Res.Status));Assert.equal(F.Calls.length,0)}});
Test('wrong password or different verified user never writes',async()=>{for(const Flag of ['Wrong','Other']){const F=Fixture({[Flag]:true});await F.Run();Assert.equal(F.Res.Status,401);Assert.ok(!F.Calls.some(C=>C[0]==='ChangeOwnUsername'||C[0]==='Update'))}});
Test('rate limit and unavailable limiter fail closed',async()=>{for(const Flag of ['Limited','LimitError']){const F=Fixture({[Flag]:true});await F.Run();Assert.ok([429,503].includes(F.Res.Status));Assert.ok(!F.Calls.some(C=>C[0]==='Verify'))}});
Test('username uses authenticated identity and clears verification session',async()=>{const F=Fixture();F.Req.body.TargetUserID='victim';await F.Run();Assert.equal(F.Res.Status,200);Assert.deepEqual(F.Calls.find(C=>C[0]==='ChangeOwnUsername')[1],{TargetUserID:'user-a',NewUsername:'new-name'});Assert.equal(F.Calls.at(-1)[1].scope,'local')});
Test('email requests confirmation rather than overwriting profile email',async()=>{const F=Fixture();F.Req.body.Action='Email';F.Req.body.Value='new@example.invalid';await F.Run();Assert.equal(F.Res.Body.Status,'EmailPending');Assert.deepEqual(F.Calls.find(C=>C[0]==='Update')[1],{email:'new@example.invalid'})});
Test('password includes current password and revokes sessions',async()=>{const F=Fixture();F.Req.body.Action='Password';F.Req.body.Value='a much longer passphrase';await F.Run();Assert.equal(F.Res.Body.Status,'PasswordChanged');Assert.equal(F.Calls.find(C=>C[0]==='Update')[1].current_password,'old-password');Assert.equal(F.Calls.at(-1)[1].scope,'global')});
Test('partial session-revocation failure is reported honestly',async()=>{const F=Fixture({SignOutError:true});F.Req.body.Action='Password';F.Req.body.Value='a much longer passphrase';await F.Run();Assert.equal(F.Res.Body.SignOutComplete,false)});
Test('Account English and Malay have complete matching keys',()=>{Assert.deepEqual(Object.keys(AccountEnglish).sort(),Object.keys(AccountMalay).sort());for(const Value of Object.values(AccountMalay))Assert.ok(Value.trim());Assert.equal(AccountEnglish.Email,'Email');Assert.equal(AccountMalay.Email,'Email')});

Test('PIN can roll out without enabling username email or password',async()=>{const F=Fixture({Env:{AccountChangesEnabled:'false',PINChangesEnabled:'true'}});F.Req.body={Action:'SetPIN',Value:'0427',CurrentPassword:'old-password'};await F.Run();Assert.equal(F.Res.Status,200);Assert.deepEqual(F.Calls.find(C=>C[0]==='ChangeOwnPIN')[1],{TargetUserID:'user-a',NewPIN:'0427'});const G=Fixture({Env:{AccountChangesEnabled:'false',PINChangesEnabled:'true'}});await G.Run();Assert.equal(G.Res.Status,503)});
Test('PIN gate and numeric payload reject before password verification',async()=>{for(const Numeric of [false,true]){const F=Fixture({Env:{PINChangesEnabled:Numeric?'true':'false'}});F.Req.body={Action:'SetPIN',Value:Numeric?1234:'1234',CurrentPassword:'old-password'};await F.Run();Assert.ok([400,503].includes(F.Res.Status));Assert.equal(F.Calls.length,0)}});
Test('clearing PIN still verifies password and targets current account',async()=>{const F=Fixture();F.Req.body={Action:'DisablePIN',CurrentPassword:'old-password',TargetUserID:'victim'};await F.Run();Assert.equal(F.Res.Status,200);Assert.ok(F.Calls.some(C=>C[0]==='Verify'));Assert.deepEqual(F.Calls.find(C=>C[0]==='ChangeOwnPIN')[1],{TargetUserID:'user-a',NewPIN:null})});
